[shell]
     program = "/bin/zsh"

[font]
     normal = { family = '0xProto Nerd Font Mono', style = 'Regular' }

[window]
     opacity = 0.75

[colors.normal]
     black = "#151720"
     red = "#dd6777"
     green = "#90ceaa"
     yellow = "#ecd3a0"
     blue = "#86aaec"
     magenta = "#c296eb"
     cyan = "#93cee9"
     white = "#cbced3"

[colors.bright]
     black = "#4f5572"
     red = "#e26c7c"
     green = "#95d3af"
     yellow = "#f1d8a5"
     blue = "#8baff1"
     magenta = "#c79bf0"
     cyan = "#98d3ee"
     white = "#d0d3d8"
